In [65]:
from pathlib import Path
import pandas as pd
import numpy as np

## Preprocessed Bereich:

#### .npy-Datei von 001-000:

In [66]:
data = np.load("../data/Dataset/Preprocessed/Inductiv_Probes/001/001-000.npy")

In [67]:
print(type(data))
print(data.shape)
print(data.dtype)
print(data[:, -1]) # letzte

<class 'numpy.ndarray'>
(4, 19909)
float64
[21.042       0.02830047  0.23695214  0.56079739]

## Raw Bereich:

#### .csv-Datei von 001-000:

In [68]:
pfadCSV001_000 = Path("../data/Dataset/Raw/inductive_Probes/001/001-000.csv")

CSV001_000 = pd.read_csv(
    pfadCSV001_000
)

display(CSV001_000.tail(1)) # letzte

print(CSV001_000.shape)

       Time (s)  Trigger (V)  Taster 1 (mm)  Taster 2 (mm)  Taster 3 (mm)
21043    21.043    24.014523       0.028143       0.237031       0.560954

(21044, 5)

## Schnittstellen:

In [69]:
# Zeit stimmt nicht überein zwischen Raw und Preprocessed beim letzten, deshalb schauen:

raw21042 = CSV001_000[
    CSV001_000["Time (s)"] == 21.042
]

display(raw21042)

print(data[:, -1])

       Time (s)  Trigger (V)  Taster 1 (mm)  Taster 2 (mm)  Taster 3 (mm)
21042    21.042    24.072506         0.0283       0.236952       0.560797

[21.042       0.02830047  0.23695214  0.56079739]

##### Grund:

##### Preprocessed bedeutet, dass die Daten verändert oder ausgeschnitten wurden. Die .npy muss also nicht bis exakt zur letzten Raw Zeile gehen. Die letzte .npy Zeile muss also nicht die letzte .csv Zeile entsprechen, entspricht eher die vorletzte .csv Zeile.

## Notizen:

* 001 ist die langsamere SchweißKonfiguration, 002 die schnellere.
* 001 ca. 1 m/min Schweizgeschwindigkeit und 002 5 m/min Schweißgeschwindigkeit, etwa 5 mal schneller
* Ordner Inductive_Probes enthält für jede Schweißung eine eigene CSV-Datei
* CSV besteht aus Time (s), Trigger (V), Taster 1 bis Taster 3
* Zeit wird in ms gezählt, ca. 1000Hz Abtastrate
* LWIR enthält für jede Schweißung eine bestimme Anzahl an .tiff-Dateien, diese sind einzelne LWIR-Wärmebilder
* Sound/Unsound bedeuten?
* Labels?